name: Terraform Security Scan

on:
  push:
    branches: [prod, staging, dev]
  pull_request:
    branches: [prod]

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: tfsec .
